# Generated by Django 3.2.16 on 2023-05-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50)),
                ('slug_name', models.SlugField(max_length=200, unique=True)),
                ('weight', models.PositiveIntegerField(default=0, help_text='Weight of the container in gr.', verbose_name='weight')),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'containers',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(help_text='Name of the provider.', max_length=50, verbose_name='name')),
                ('phone', models.CharField(help_text='Phone of the provider.', max_length=50, verbose_name='phone')),
                ('address', models.CharField(help_text='Address of the provider.', max_length=50, verbose_name='address')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=50)),
                ('slug_name', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('total_amount_paid', models.PositiveIntegerField(default=0, help_text='Total invoice amount.', verbose_name='Total amount paid')),
                ('date', models.DateField(help_text='Date of the purchase.', verbose_name='date')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='stock.provider')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='ProviderDeliveryDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], help_text='Day name.', max_length=100, verbose_name='Delivery day')),
                ('day_number', models.IntegerField(default=0, help_text='Day number monday is 0 and sunday 6.')),
                ('hour', models.TimeField(blank=True, null=True, verbose_name='Delivery hour')),
                ('is_active', models.BooleanField(default=True, help_text='Set to false to disable a delivery day.', verbose_name='Active')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_days', to='stock.provider')),
            ],
            options={
                'verbose_name': 'provider delivery day',
                'verbose_name_plural': 'provider delivery days',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock of the product.', verbose_name='stock')),
                ('stock_min', models.PositiveIntegerField(blank=True, default=0, help_text='Minimum stock of the product.', null=True, verbose_name='stock min')),
                ('stock_max', models.PositiveIntegerField(blank=True, default=0, help_text='Maximum stock of the product.', null=True, verbose_name='stock max')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.unitofmeasure')),
            ],
            options={
                'verbose_name': 'product stock',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Product quantity of the purchase.', verbose_name='stock')),
                ('amount_paid', models.PositiveIntegerField(blank=True, default=0, help_text='Total amount paid for the product.', null=True, verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='products.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stock.purchases')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.unitofmeasure')),
            ],
            options={
                'verbose_name': 'product purchase',
            },
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Stock of the product.', verbose_name='stock')),
                ('stock_min', models.PositiveIntegerField(default=0, help_text='Minimum stock of the product.', verbose_name='stock min')),
                ('stock_max', models.PositiveIntegerField(default=0, help_text='Maximum stock of the product.', verbose_name='stock max')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.ingredientcontainer')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.unitofmeasure')),
            ],
            options={
                'verbose_name': 'ingredient stock',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Ingredient quantity of the purchase.', verbose_name='quantity')),
                ('amount_paid', models.PositiveIntegerField(blank=True, default=0, help_text='Total amount paid for the ingredient.', null=True, verbose_name='price')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='products.ingredient')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='stock.purchases')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Ingredient purchase',
            },
        ),
    ]
